# Generated by Django 4.1.13 on 2024-02-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(db_column='context', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100)),
            ],
        ),
    ]
